# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/c2i/',
                'doc_host': 'https://callmephilip.github.io',
                'git_url': 'https://github.com/callmephilip/c2i/',
                'lib_path': 'c2i'},
  'syms': { 'c2i.bsky': {'c2i.bsky.main': ('bsky.html#main', 'c2i/bsky.py')},
            'c2i.core': {'c2i.core.generate_screenshot': ('core.html#generate_screenshot', 'c2i/core.py')}}}
