"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['generate_screenshot']

# %% ../00_core.ipynb 2
import os, uuid
from string import Template
from playwright.async_api import async_playwright

# %% ../00_core.ipynb 4
async def generate_screenshot(code, code_file = "./playground.html", screenshots_dir = "./screenshots"):
  if not os.path.exists(screenshots_dir): os.makedirs(screenshots_dir)
  screenshot_file = os.path.join(screenshots_dir, f"{uuid.uuid4()}.png")

  # html escape code
  cc = code.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
  # remove trailing whitespaces and line breaks
  cc = cc.strip()

  with open(code_file, 'r') as file: playground = Template(file.read()).substitute(code=cc)

  async with async_playwright() as playwright:
    webkit = playwright.webkit
    browser = await webkit.launch()
    browser_context = await browser.new_context(device_scale_factor=2)
    page = await browser_context.new_page()
    await page.set_content(playground)
    await page.locator("#code").screenshot(path=screenshot_file)
    await browser.close()

  return screenshot_file
